pluginManagement {
    repositories {
        maven {
            name = 'GTNH Maven'
            url = 'https://nexus.gtnewhorizons.com/repository/public/'
            mavenContent {
                includeGroupByRegex('com\\.gtnewhorizons\\..+')
                includeGroup('com.gtnewhorizons')
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'alpha'
